mysite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls'))
]

polls/urls.py
from django.conf.urls import url

from . import views
app_name = 'polls'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=256)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now()-datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=256)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import HttpResponse, HttpResponseRedirect, reverse, render
from django.shortcuts import get_object_or_404
from django.template import loader
from .models import Question, Choice


def index(request):
    latest_question_list = Question.objects.order_by('pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    template = loader.get_template('polls/index.html')
    return HttpResponse(template.render(context, request))


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/result.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't make a choice",
        },)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

templates/polls/detail.html
<!DOCTYPE html>
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method = "post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <lable for="choice{{ forloop.counter }}">{{ choice.choice_text }}</lable>
{% endfor %}
<input type="submit" value="vote" />
</form>

templates/polls/index.html
<!DOCTYPE html>
{% if latest_question_list %}
    {% for q in latest_question_list %}
    <ul>
        <li><a href = "/polls/{{ q.id }}/">{{ q.question_text }}</a></li>
    </ul>
    {% endfor %}
{% else %}
    <p> No polls are available.</p>
{% endif %}

templates/polls/result.html
<!DOCTYPE html>
<h1>{{ question.question_text }}</h1>
{% for choice in question.choice_set.all %}
    <ul>
        <li>{{ choice.choice_text }}--{{ choice.votes }}vote{{ choice.votes|pluralize }}</li>
    </ul>
{% endfor %}
<a href = {% url 'polls:detail' question.id %} > Vote again? </a>